### ISSUE TITLE
Create profile generates errors when ignoring instructions

### ISSUE THREAD

**Issue by TimVa** [Alex9779/BigBox-S3D-Profile-Builder#2]
When running the create profile script, and just <enter><enter> you get some errors : 
BigBox S3D Profile Builder

Select your leveling mechanism:

1 - ABL (auto bed leveling)
2 - MBL (mesh/manual bed leveling)

Type 1 or 2 then press ENTER:
You did not enter a number!

Do you have a PEI build plate?

1 - No
2 - Yes

Type 1 or 2 then press ENTER:
You did not enter a number!

Generating profiles...
^C

Error in xsl:when/@test on line 168 column 48 of BigBox%20Dual.xsl:
  FORG0001: String to double conversion: no digits found
String to double conversion: no digits found

Error in xsl:when/@test on line 198 column 48 of BigBox%20Hybrid-Dual%20Mirrored.xsl:
  FORG0001: String to double conversion: no digits found
String to double conversion: no digits found
Error in xsl:when/@test on line 189 column 48 of BigBox%20Hybrid-Dual.xsl:
  FORG0001: String to double conversion: no digits found
String to double conversion: no digits found
Error in xsl:when/@test on line 137 column 48 of BigBox%20Hybrid-Pro.xsl:
  FORG0001: String to double conversion: no digits found
String to double conversion: no digits found
Error in xsl:when/@test on line 137 column 48 of BigBox%20Pro.xsl:
  FORG0001: String to double conversion: no digits found
String to double conversion: no digits found

Profiles generated!

**Comment by Alex9779** [comment]
Ya if you don't enter number then this fails. The XSLT has default values but those are over written by the call which has nothing in it in this case...
We could drop out if you enter no number, or ask over and over again until there is valid input...

**Comment by TimVa** [comment]
I would default to the most logical choice, being 1-1 for the moment no?

**Comment by Alex9779** [comment]
Yeah well I did that in the XSL but didn't realize that if you don't enter something when using the batch an empty value is set. Empty is not the same like non existent and only if you don't set it the XSL default value kicks in...

**Comment by TimVa** [comment]
You made an important lessons here, you learned something today, you can now go home :) 👍

**Comment by Alex9779** [comment]
This is a freak tool. Doesn't need to be fail safe :D
